### ISSUE TITLE
Make it so Rich and Jacob can edit Jira ticket metadata (tags and labels and dates and stuff)

### ISSUE THREAD

**Issue by richkingsford** [visdesignlab/copy-number#4]
@alexsb or @clementsan - could you please give us edit access?  I'm hoping this will make it easier for us to triage, stay on the same page, discuss tickets, and keep the MVP lean. 

thanks

**Comment by alexsb** [comment]
Sure - I do need your github usernames for that. @richkingsford - yours was obvious, but I can't find Jacob's. 

You can accept my invitation here: 

https://github.com/visdesignlab/copy-number/invitations

**Comment by durtschi** [comment]
Hi @alexsb. My github username is durtschi

**Comment by alexsb** [comment]
Added @durtschi too! 

Closing
