### ISSUE TITLE
Put all the MVP stories into github issues

### ISSUE THREAD

**Issue by richkingsford** [visdesignlab/copy-number#5]
I'm happy to do this.  Let's please mark the question marks as "To triage" or something

**Comment by richkingsford** [comment]
@alex-r-bigelow you ok if I plug these in as github issues and then we can triage together?
See [CNV Visualization Tool User Stories 9-13-17.docx](https://github.com/visdesignlab/copy-number/files/1311689/CNV.Visualization.Tool.User.Stories.9-13-17.docx)

**Comment by alexsb** [comment]
Yes, btw I'm @alexsb - we have another Alex in the lab ;)

**Comment by richkingsford** [comment]
@alexsb whoops - got it.

I'll add the stories then close.

**Comment by alexsb** [comment]
I've created  a first milestone here: https://github.com/visdesignlab/copy-number/milestone/1
